#!/bin/sh
#
# Name: todoarchive.sh
# Author: Regina Collecchia (ginacollecchia@gmail.com)
# Date: Jan 15, 2015
# Description: 
# Shell script to write all of the completed items in a day to file. 
# Compares the completed items (deletions) to added items (additions) to
# evaluate what was done. Incomplete, since it would seem that an item
# added in the day in question and completed during that same day would
# not be tracked.
#
# Monthly digest of these files is generated by todomonthlydigest.sh.

cd ~/Library/Application\ Support/Notational\ Data/Archive/
# save current to do list, "Work.txt", as my work to-do as of today
scp ../Work.txt work_today.txt

# just need to compare the items on the completed list to items on the work today list to delete any duplicates
# workaround until I figure out the right way:
comm -23 all_completed_items_sorted.txt all_new_items_sorted.txt > todays_completed_shite.txt

# first make a directory folder if it doesn't exist
mkdir -p "$(date +%Y/%m)"
# save to the archive
scp todays_completed_shite.txt "$(date +%Y/%m/%m-%d-%Y)_Completed_Items.txt"
# echo "Completed items successfully saved to disk: "
# echo "" | more todays_completed_shite.txt

# cleanup: copy today's work to file for later comparison
scp work_today.txt work_yesterday.txt
scp work_today.txt work_today_temp.txt
rm work_today.txt
rm todays_completed_shite.txt
rm all_new_items_sorted.txt
rm all_completed_items_sorted.txt